In [ ]:
Nama : Abdul Gofir Samjani
NIM : 202310370311136

In [1]:
%pip install fastexcel

Collecting fastexcel
  Downloading fastexcel-0.21.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.2 kB)
Downloading fastexcel-0.21.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 1.7 MB/s  0:00:02 eta 0:00:01
Installing collected packages: fastexcel
Successfully installed fastexcel-0.21.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
DATA_PATH = "../data/raw/online_retail_II.xlsx"

In [3]:
import polars as pl

sheet_2009_2010 = pl.read_excel(
    DATA_PATH,
    sheet_name="Year 2009-2010"
)

sheet_2010_2011 = pl.read_excel(
    DATA_PATH,
    sheet_name="Year 2010-2011"
)

df = pl.concat([sheet_2009_2010, sheet_2010_2011])

df.head()

shape: (5, 8)
┌─────────┬───────────┬────────────────┬──────────┬────────────────┬───────┬─────────────┬─────────┐
│ Invoice ┆ StockCode ┆ Description    ┆ Quantity ┆ InvoiceDate    ┆ Price ┆ Customer ID ┆ Country │
│ ---     ┆ ---       ┆ ---            ┆ ---      ┆ ---            ┆ ---   ┆ ---         ┆ ---     │
│ i64     ┆ str       ┆ str            ┆ i64      ┆ datetime[ms]   ┆ f64   ┆ i64         ┆ str     │
╞═════════╪═══════════╪════════════════╪══════════╪════════════════╪═══════╪═════════════╪═════════╡
│ 489434  ┆ 85048     ┆ 15CM CHRISTMAS ┆ 12       ┆ 2009-12-01     ┆ 6.95  ┆ 13085       ┆ United  │
│         ┆           ┆ GLASS BALL 20  ┆          ┆ 07:45:00       ┆       ┆             ┆ Kingdom │
│         ┆           ┆ L…             ┆          ┆                ┆       ┆             ┆         │
│ 489434  ┆ 79323P    ┆ PINK CHERRY    ┆ 12       ┆ 2009-12-01     ┆ 6.75  ┆ 13085       ┆ United  │
│         ┆           ┆ LIGHTS         ┆          ┆ 07:45:00       ┆       ┆             ┆ Kingdom │
│ 489434  ┆ 79323W    ┆ WHITE CHERRY   ┆ 12       ┆ 2009-12-01     ┆ 6.75  ┆ 13085       ┆ United  │
│         ┆           ┆ LIGHTS         ┆          ┆ 07:45:00       ┆       ┆             ┆ Kingdom │
│ 489434  ┆ 22041     ┆ RECORD FRAME   ┆ 48       ┆ 2009-12-01     ┆ 2.1   ┆ 13085       ┆ United  │
│         ┆           ┆ 7" SINGLE SIZE ┆          ┆ 07:45:00       ┆       ┆             ┆ Kingdom │
│ 489434  ┆ 21232     ┆ STRAWBERRY     ┆ 24       ┆ 2009-12-01     ┆ 1.25  ┆ 13085       ┆ United  │
│         ┆           ┆ CERAMIC        ┆          ┆ 07:45:00       ┆       ┆             ┆ Kingdom │
│         ┆           ┆ TRINKET BOX    ┆          ┆                ┆       ┆             ┆         │
└─────────┴───────────┴────────────────┴──────────┴────────────────┴───────┴─────────────┴─────────┘

In [4]:
df.shape

(1067371, 8)

In [5]:
df.describe()

shape: (9, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ Invoice   ┆ StockCode ┆ Descripti ┆ … ┆ InvoiceDa ┆ Price     ┆ Customer  ┆ Country  │
│ ---       ┆ ---       ┆ ---       ┆ on        ┆   ┆ te        ┆ ---       ┆ ID        ┆ ---      │
│ str       ┆ f64       ┆ str       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ str      │
│           ┆           ┆           ┆ str       ┆   ┆ str       ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1.047871e ┆ 1067371   ┆ 1062989   ┆ … ┆ 1067371   ┆ 1.067371e ┆ 824364.0  ┆ 1067371  │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆ 6         ┆           ┆          │
│ null_coun ┆ 19500.0   ┆ 0         ┆ 4382      ┆ … ┆ 0         ┆ 0.0       ┆ 243007.0  ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 537608.14 ┆ null      ┆ null      ┆ … ┆ 2011-01-0 ┆ 4.649388  ┆ 15324.638 ┆ null     │
│           ┆ 9932      ┆           ┆           ┆   ┆ 2 21:13:5 ┆           ┆ 504       ┆          │
│           ┆           ┆           ┆           ┆   ┆ 5.394000  ┆           ┆           ┆          │
│ std       ┆ 26662.450 ┆ null      ┆ null      ┆ … ┆ null      ┆ 123.55305 ┆ 1697.4644 ┆ null     │
│           ┆ 447       ┆           ┆           ┆   ┆           ┆ 9         ┆ 5         ┆          │
│ min       ┆ 489434.0  ┆ 10002     ┆ DOORMAT   ┆ … ┆ 2009-12-0 ┆ -53594.36 ┆ 12346.0   ┆ Australi │
│           ┆           ┆           ┆ UNION     ┆   ┆ 1         ┆           ┆           ┆ a        │
│           ┆           ┆           ┆ JACK GUNS ┆   ┆ 07:45:00  ┆           ┆           ┆          │
│           ┆           ┆           ┆ AND …     ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ 515305.0  ┆ null      ┆ null      ┆ … ┆ 2010-07-0 ┆ 1.25      ┆ 13975.0   ┆ null     │
│           ┆           ┆           ┆           ┆   ┆ 9         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 09:46:00  ┆           ┆           ┆          │
│ 50%       ┆ 537638.0  ┆ null      ┆ null      ┆ … ┆ 2010-12-0 ┆ 2.1       ┆ 15255.0   ┆ null     │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 15:28:00  ┆           ┆           ┆          │
│ 75%       ┆ 561006.0  ┆ null      ┆ null      ┆ … ┆ 2011-07-2 ┆ 4.15      ┆ 16797.0   ┆ null     │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 10:23:00  ┆           ┆           ┆          │
│ max       ┆ 581587.0  ┆ m         ┆ wrongly   ┆ … ┆ 2011-12-0 ┆ 38970.0   ┆ 18287.0   ┆ West     │
│           ┆           ┆           ┆ sold sets ┆   ┆ 9         ┆           ┆           ┆ Indies   │
│           ┆           ┆           ┆           ┆   ┆ 12:50:00  ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
df.null_count()

shape: (1, 8)
┌─────────┬───────────┬─────────────┬──────────┬─────────────┬───────┬─────────────┬─────────┐
│ Invoice ┆ StockCode ┆ Description ┆ Quantity ┆ InvoiceDate ┆ Price ┆ Customer ID ┆ Country │
│ ---     ┆ ---       ┆ ---         ┆ ---      ┆ ---         ┆ ---   ┆ ---         ┆ ---     │
│ u32     ┆ u32       ┆ u32         ┆ u32      ┆ u32         ┆ u32   ┆ u32         ┆ u32     │
╞═════════╪═══════════╪═════════════╪══════════╪═════════════╪═══════╪═════════════╪═════════╡
│ 19500   ┆ 0         ┆ 4382        ┆ 0        ┆ 0           ┆ 0     ┆ 243007      ┆ 0       │
└─────────┴───────────┴─────────────┴──────────┴─────────────┴───────┴─────────────┴─────────┘

In [7]:
df.schema

Schema([('Invoice', Int64),
        ('StockCode', String),
        ('Description', String),
        ('Quantity', Int64),
        ('InvoiceDate', Datetime(time_unit='ms', time_zone=None)),
        ('Price', Float64),
        ('Customer ID', Int64),
        ('Country', String)])

In [8]:
df.select([
    pl.col("InvoiceDate").min().alias("tanggal_awal"),
    pl.col("InvoiceDate").max().alias("tanggal_akhir")
])

shape: (1, 2)
┌─────────────────────┬─────────────────────┐
│ tanggal_awal        ┆ tanggal_akhir       │
│ ---                 ┆ ---                 │
│ datetime[ms]        ┆ datetime[ms]        │
╞═════════════════════╪═════════════════════╡
│ 2009-12-01 07:45:00 ┆ 2011-12-09 12:50:00 │
└─────────────────────┴─────────────────────┘

In [9]:
df.select([
    pl.col("Invoice").n_unique().alias("jumlah_invoice"),
    pl.col("Customer ID").n_unique().alias("jumlah_customer"),
    pl.col("Country").n_unique().alias("jumlah_negara"),
])

shape: (1, 3)
┌────────────────┬─────────────────┬───────────────┐
│ jumlah_invoice ┆ jumlah_customer ┆ jumlah_negara │
│ ---            ┆ ---             ┆ ---           │
│ u32            ┆ u32             ┆ u32           │
╞════════════════╪═════════════════╪═══════════════╡
│ 45331          ┆ 5943            ┆ 43            │
└────────────────┴─────────────────┴───────────────┘

In [10]:
df.group_by("Country").len().sort("len", descending=True).head(10)

shape: (10, 2)
┌────────────────┬────────┐
│ Country        ┆ len    │
│ ---            ┆ ---    │
│ str            ┆ u32    │
╞════════════════╪════════╡
│ United Kingdom ┆ 981330 │
│ EIRE           ┆ 17866  │
│ Germany        ┆ 17624  │
│ France         ┆ 14330  │
│ Netherlands    ┆ 5140   │
│ Spain          ┆ 3811   │
│ Switzerland    ┆ 3189   │
│ Belgium        ┆ 3123   │
│ Portugal       ┆ 2620   │
│ Australia      ┆ 1913   │
└────────────────┴────────┘

In [11]:
df = df.with_columns(
    (pl.col("Quantity") * pl.col("Price")).alias("TotalPrice")
)

df.head()

shape: (5, 9)
┌─────────┬───────────┬───────────────┬──────────┬───┬───────┬──────────────┬─────────┬────────────┐
│ Invoice ┆ StockCode ┆ Description   ┆ Quantity ┆ … ┆ Price ┆ Customer ID  ┆ Country ┆ TotalPrice │
│ ---     ┆ ---       ┆ ---           ┆ ---      ┆   ┆ ---   ┆ ---          ┆ ---     ┆ ---        │
│ i64     ┆ str       ┆ str           ┆ i64      ┆   ┆ f64   ┆ i64          ┆ str     ┆ f64        │
╞═════════╪═══════════╪═══════════════╪══════════╪═══╪═══════╪══════════════╪═════════╪════════════╡
│ 489434  ┆ 85048     ┆ 15CM          ┆ 12       ┆ … ┆ 6.95  ┆ 13085        ┆ United  ┆ 83.4       │
│         ┆           ┆ CHRISTMAS     ┆          ┆   ┆       ┆              ┆ Kingdom ┆            │
│         ┆           ┆ GLASS BALL 20 ┆          ┆   ┆       ┆              ┆         ┆            │
│         ┆           ┆ L…            ┆          ┆   ┆       ┆              ┆         ┆            │
│ 489434  ┆ 79323P    ┆ PINK CHERRY   ┆ 12       ┆ … ┆ 6.75  ┆ 13085        ┆ United  ┆ 81.0       │
│         ┆           ┆ LIGHTS        ┆          ┆   ┆       ┆              ┆ Kingdom ┆            │
│ 489434  ┆ 79323W    ┆ WHITE CHERRY  ┆ 12       ┆ … ┆ 6.75  ┆ 13085        ┆ United  ┆ 81.0       │
│         ┆           ┆ LIGHTS        ┆          ┆   ┆       ┆              ┆ Kingdom ┆            │
│ 489434  ┆ 22041     ┆ RECORD FRAME  ┆ 48       ┆ … ┆ 2.1   ┆ 13085        ┆ United  ┆ 100.8      │
│         ┆           ┆ 7" SINGLE     ┆          ┆   ┆       ┆              ┆ Kingdom ┆            │
│         ┆           ┆ SIZE          ┆          ┆   ┆       ┆              ┆         ┆            │
│ 489434  ┆ 21232     ┆ STRAWBERRY    ┆ 24       ┆ … ┆ 1.25  ┆ 13085        ┆ United  ┆ 30.0       │
│         ┆           ┆ CERAMIC       ┆          ┆   ┆       ┆              ┆ Kingdom ┆            │
│         ┆           ┆ TRINKET BOX   ┆          ┆   ┆       ┆              ┆         ┆            │
└─────────┴───────────┴───────────────┴──────────┴───┴───────┴──────────────┴─────────┴────────────┘

In [12]:
df.group_by("Country").agg(
    pl.col("TotalPrice").sum().alias("total_sales")
).sort("total_sales", descending=True).head(10)

shape: (10, 2)
┌────────────────┬─────────────┐
│ Country        ┆ total_sales │
│ ---            ┆ ---         │
│ str            ┆ f64         │
╞════════════════╪═════════════╡
│ United Kingdom ┆ 1.6383e7    │
│ EIRE           ┆ 615519.55   │
│ Netherlands    ┆ 548524.95   │
│ Germany        ┆ 417988.561  │
│ France         ┆ 328191.8    │
│ Australia      ┆ 167129.07   │
│ Switzerland    ┆ 99728.76    │
│ Spain          ┆ 91859.48    │
│ Sweden         ┆ 87809.42    │
│ Denmark        ┆ 65741.09    │
└────────────────┴─────────────┘